name: rohd_cosim
version: 0.2.0
description: Cosimulation for the Rapid Open Hardware Development (ROHD) framework with other simulators
homepage: https://github.com/intel/rohd-cosim
repository: https://github.com/intel/rohd-cosim
issue_tracker: https://github.com/intel/rohd-cosim/issues
documentation: https://intel.github.io/rohd-cosim/rohd_cosim/rohd_cosim-library.html

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  logging: ^1.0.2
  meta: ^1.8.0
  rohd: ^0.5.0
  synchronized: ^3.0.0

dev_dependencies:
  args: ^2.3.1
  test: ^1.17.3
