name: rohd_cosim
description: Cosimulation for the Rapid Open Hardware Development (ROHD) framework with other simulators
version: 0.1.0
homepage: https://github.com/intel/rohd-cosim
repository: https://github.com/intel/rohd-cosim
issue_tracker: https://github.com/intel/rohd-cosim/issues
documentation: https://intel.github.io/rohd-cosim/rohd_cosim/rohd_cosim-library.html

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  logging: ^1.0.2
  meta: ^1.8.0
  rohd: ^0.4.2
  synchronized: ^3.0.0

dev_dependencies:
  args: ^2.3.1
  lints: ^2.0.0
  test: ^1.17.3
